import numpy as np


class PotentialFieldComputer:
    def __init__(self, q_repel, q_attract, dist_threshold):
        """

        :param q_repel: coefficient of repelling force between vehicle and obstacles
        :param q_attract: coefficient of attraction force between vehicle and target point
        :param dist_threshold: sphere of influence of individual obstacle point. Repelling force is zero if the distance
        to the point is more than dist_threshold
        """
        self.q_repel = q_repel
        self.q_attract = q_attract
        self.dist_threshold = dist_threshold

    def compute_trajectory(self, point_cloud, vehicle_coord, target_coord, speed, dt=0.1, n_points=20):
        """
        Computes a local trajectory by simulating a particle motion inside the potential field generated by target point
        and points from obstacle point cloud

        :param point_cloud: np.array(shape=(N, 3)) containing the point cloud
        :param vehicle_coord: np.array(shape=(3)) current coordinate of vehicle.
        :param target_coord: np.array(shape=(3)) coordinate of the target point
        :param speed: speed of particle motion
        :param dt: time step of motion equation solver
        :param n_points: number of points in motion equation solution
        :return: np.array(shape=(n_points, 3)) local trajectory
        """
        trajectory = np.zeros(shape=(n_points, 3))
        trajectory[0] = vehicle_coord
        for i in range(1, n_points):
            if len(point_cloud) == 0:
                repelling_force = np.zeros(3)
            else:
                diff = point_cloud - vehicle_coord.reshape(1, 3)
                dist = np.linalg.norm(diff, axis=1, keepdims=True)
                repel_directions = -diff / dist

                distance_component = (1 / dist - 1 / self.dist_threshold)

                nullifier = np.ones_like(diff)
                nullifier[dist.reshape(-1) > self.dist_threshold, :] = np.zeros(3)

                repelling_force = np.sum(repel_directions * self.q_repel * nullifier * distance_component, axis=0)

            attraction_force = 2 * self.q_attract * (target_coord - vehicle_coord) / np.linalg.norm(target_coord - vehicle_coord)

            force = attraction_force + repelling_force
            velocity = speed * force / np.linalg.norm(force)
            vehicle_coord = vehicle_coord + velocity * dt

            trajectory[i] = vehicle_coord

        return trajectory.copy()
